export default [
  {
    login: "sahabiswajit600",
    id: 54775888,
    node_id: "MDQ6VXNlcjU0Nzc1ODg4",
    avatar_url: "https://avatars.githubusercontent.com/u/54775888?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sahabiswajit600",
    html_url: "https://github.com/sahabiswajit600",
    followers_url: "https://api.github.com/users/sahabiswajit600/followers",
    following_url:
      "https://api.github.com/users/sahabiswajit600/following{/other_user}",
    gists_url: "https://api.github.com/users/sahabiswajit600/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sahabiswajit600/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/sahabiswajit600/subscriptions",
    organizations_url: "https://api.github.com/users/sahabiswajit600/orgs",
    repos_url: "https://api.github.com/users/sahabiswajit600/repos",
    events_url: "https://api.github.com/users/sahabiswajit600/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sahabiswajit600/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "adityabhagat007",
    id: 55406090,
    node_id: "MDQ6VXNlcjU1NDA2MDkw",
    avatar_url: "https://avatars.githubusercontent.com/u/55406090?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/adityabhagat007",
    html_url: "https://github.com/adityabhagat007",
    followers_url: "https://api.github.com/users/adityabhagat007/followers",
    following_url:
      "https://api.github.com/users/adityabhagat007/following{/other_user}",
    gists_url: "https://api.github.com/users/adityabhagat007/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/adityabhagat007/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/adityabhagat007/subscriptions",
    organizations_url: "https://api.github.com/users/adityabhagat007/orgs",
    repos_url: "https://api.github.com/users/adityabhagat007/repos",
    events_url: "https://api.github.com/users/adityabhagat007/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/adityabhagat007/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Rijudas149",
    id: 63858941,
    node_id: "MDQ6VXNlcjYzODU4OTQx",
    avatar_url: "https://avatars.githubusercontent.com/u/63858941?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Rijudas149",
    html_url: "https://github.com/Rijudas149",
    followers_url: "https://api.github.com/users/Rijudas149/followers",
    following_url:
      "https://api.github.com/users/Rijudas149/following{/other_user}",
    gists_url: "https://api.github.com/users/Rijudas149/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Rijudas149/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Rijudas149/subscriptions",
    organizations_url: "https://api.github.com/users/Rijudas149/orgs",
    repos_url: "https://api.github.com/users/Rijudas149/repos",
    events_url: "https://api.github.com/users/Rijudas149/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Rijudas149/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Anubrata450",
    id: 64024571,
    node_id: "MDQ6VXNlcjY0MDI0NTcx",
    avatar_url: "https://avatars.githubusercontent.com/u/64024571?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Anubrata450",
    html_url: "https://github.com/Anubrata450",
    followers_url: "https://api.github.com/users/Anubrata450/followers",
    following_url:
      "https://api.github.com/users/Anubrata450/following{/other_user}",
    gists_url: "https://api.github.com/users/Anubrata450/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Anubrata450/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Anubrata450/subscriptions",
    organizations_url: "https://api.github.com/users/Anubrata450/orgs",
    repos_url: "https://api.github.com/users/Anubrata450/repos",
    events_url: "https://api.github.com/users/Anubrata450/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Anubrata450/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Sneha-ban07",
    id: 64071410,
    node_id: "MDQ6VXNlcjY0MDcxNDEw",
    avatar_url: "https://avatars.githubusercontent.com/u/64071410?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Sneha-ban07",
    html_url: "https://github.com/Sneha-ban07",
    followers_url: "https://api.github.com/users/Sneha-ban07/followers",
    following_url:
      "https://api.github.com/users/Sneha-ban07/following{/other_user}",
    gists_url: "https://api.github.com/users/Sneha-ban07/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Sneha-ban07/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Sneha-ban07/subscriptions",
    organizations_url: "https://api.github.com/users/Sneha-ban07/orgs",
    repos_url: "https://api.github.com/users/Sneha-ban07/repos",
    events_url: "https://api.github.com/users/Sneha-ban07/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Sneha-ban07/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "shatanikmahanty",
    id: 67138059,
    node_id: "MDQ6VXNlcjY3MTM4MDU5",
    avatar_url: "https://avatars.githubusercontent.com/u/67138059?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/shatanikmahanty",
    html_url: "https://github.com/shatanikmahanty",
    followers_url: "https://api.github.com/users/shatanikmahanty/followers",
    following_url:
      "https://api.github.com/users/shatanikmahanty/following{/other_user}",
    gists_url: "https://api.github.com/users/shatanikmahanty/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/shatanikmahanty/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/shatanikmahanty/subscriptions",
    organizations_url: "https://api.github.com/users/shatanikmahanty/orgs",
    repos_url: "https://api.github.com/users/shatanikmahanty/repos",
    events_url: "https://api.github.com/users/shatanikmahanty/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/shatanikmahanty/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Bijoy-007",
    id: 67514758,
    node_id: "MDQ6VXNlcjY3NTE0NzU4",
    avatar_url: "https://avatars.githubusercontent.com/u/67514758?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Bijoy-007",
    html_url: "https://github.com/Bijoy-007",
    followers_url: "https://api.github.com/users/Bijoy-007/followers",
    following_url:
      "https://api.github.com/users/Bijoy-007/following{/other_user}",
    gists_url: "https://api.github.com/users/Bijoy-007/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Bijoy-007/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Bijoy-007/subscriptions",
    organizations_url: "https://api.github.com/users/Bijoy-007/orgs",
    repos_url: "https://api.github.com/users/Bijoy-007/repos",
    events_url: "https://api.github.com/users/Bijoy-007/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Bijoy-007/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "khaftab",
    id: 69357833,
    node_id: "MDQ6VXNlcjY5MzU3ODMz",
    avatar_url: "https://avatars.githubusercontent.com/u/69357833?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/khaftab",
    html_url: "https://github.com/khaftab",
    followers_url: "https://api.github.com/users/khaftab/followers",
    following_url:
      "https://api.github.com/users/khaftab/following{/other_user}",
    gists_url: "https://api.github.com/users/khaftab/gists{/gist_id}",
    starred_url: "https://api.github.com/users/khaftab/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/khaftab/subscriptions",
    organizations_url: "https://api.github.com/users/khaftab/orgs",
    repos_url: "https://api.github.com/users/khaftab/repos",
    events_url: "https://api.github.com/users/khaftab/events{/privacy}",
    received_events_url: "https://api.github.com/users/khaftab/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rohit123dey",
    id: 69362546,
    node_id: "MDQ6VXNlcjY5MzYyNTQ2",
    avatar_url: "https://avatars.githubusercontent.com/u/69362546?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rohit123dey",
    html_url: "https://github.com/rohit123dey",
    followers_url: "https://api.github.com/users/rohit123dey/followers",
    following_url:
      "https://api.github.com/users/rohit123dey/following{/other_user}",
    gists_url: "https://api.github.com/users/rohit123dey/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/rohit123dey/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rohit123dey/subscriptions",
    organizations_url: "https://api.github.com/users/rohit123dey/orgs",
    repos_url: "https://api.github.com/users/rohit123dey/repos",
    events_url: "https://api.github.com/users/rohit123dey/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/rohit123dey/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "darkhorse-2000",
    id: 72261729,
    node_id: "MDQ6VXNlcjcyMjYxNzI5",
    avatar_url: "https://avatars.githubusercontent.com/u/72261729?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/darkhorse-2000",
    html_url: "https://github.com/darkhorse-2000",
    followers_url: "https://api.github.com/users/darkhorse-2000/followers",
    following_url:
      "https://api.github.com/users/darkhorse-2000/following{/other_user}",
    gists_url: "https://api.github.com/users/darkhorse-2000/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/darkhorse-2000/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/darkhorse-2000/subscriptions",
    organizations_url: "https://api.github.com/users/darkhorse-2000/orgs",
    repos_url: "https://api.github.com/users/darkhorse-2000/repos",
    events_url: "https://api.github.com/users/darkhorse-2000/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/darkhorse-2000/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mannasoumo",
    id: 75923589,
    node_id: "MDQ6VXNlcjc1OTIzNTg5",
    avatar_url: "https://avatars.githubusercontent.com/u/75923589?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mannasoumo",
    html_url: "https://github.com/mannasoumo",
    followers_url: "https://api.github.com/users/mannasoumo/followers",
    following_url:
      "https://api.github.com/users/mannasoumo/following{/other_user}",
    gists_url: "https://api.github.com/users/mannasoumo/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/mannasoumo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mannasoumo/subscriptions",
    organizations_url: "https://api.github.com/users/mannasoumo/orgs",
    repos_url: "https://api.github.com/users/mannasoumo/repos",
    events_url: "https://api.github.com/users/mannasoumo/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/mannasoumo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ApratimGhosh121",
    id: 83712593,
    node_id: "MDQ6VXNlcjgzNzEyNTkz",
    avatar_url: "https://avatars.githubusercontent.com/u/83712593?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ApratimGhosh121",
    html_url: "https://github.com/ApratimGhosh121",
    followers_url: "https://api.github.com/users/ApratimGhosh121/followers",
    following_url:
      "https://api.github.com/users/ApratimGhosh121/following{/other_user}",
    gists_url: "https://api.github.com/users/ApratimGhosh121/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ApratimGhosh121/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ApratimGhosh121/subscriptions",
    organizations_url: "https://api.github.com/users/ApratimGhosh121/orgs",
    repos_url: "https://api.github.com/users/ApratimGhosh121/repos",
    events_url: "https://api.github.com/users/ApratimGhosh121/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ApratimGhosh121/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Tamalcs123",
    id: 87684531,
    node_id: "MDQ6VXNlcjg3Njg0NTMx",
    avatar_url: "https://avatars.githubusercontent.com/u/87684531?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Tamalcs123",
    html_url: "https://github.com/Tamalcs123",
    followers_url: "https://api.github.com/users/Tamalcs123/followers",
    following_url:
      "https://api.github.com/users/Tamalcs123/following{/other_user}",
    gists_url: "https://api.github.com/users/Tamalcs123/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Tamalcs123/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Tamalcs123/subscriptions",
    organizations_url: "https://api.github.com/users/Tamalcs123/orgs",
    repos_url: "https://api.github.com/users/Tamalcs123/repos",
    events_url: "https://api.github.com/users/Tamalcs123/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Tamalcs123/received_events",
    type: "User",
    site_admin: false,
  },
];
